{{- if (.Values.director).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "etherealengine.director.fullname" . }}
  namespace: {{ include "etherealengine.matchmaking-namespace" . }}
  labels:
    {{- include "etherealengine.director.labels" . | nindent 4 }}
data:
{{- if .Values.director.extraEnv }}
{{ toYaml .Values.director.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.director.config }}
  NODE_CONFIG: '{{ mustToJson .Values.director.config }}'
{{- end }}
{{- end -}}
