{{- if (.Values.director).enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "etherealengine.director.fullname" . }}
  namespace: {{ include "etherealengine.matchmaking-namespace" . }}
  labels:
    {{- include "etherealengine.director.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "etherealengine.director.serviceAccountName" . }}
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "etherealengine.director.fullname" . }}
{{- end -}}
