{{- if (.Values.director).enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etherealengine.director.fullname" . }}
  namespace: {{ include "etherealengine.matchmaking-namespace" . }}
  labels:
    {{- include "etherealengine.director.labels" . | nindent 4 }}
spec:
  type: {{ .Values.director.service.type }}
  ports:
    - port: {{ .Values.director.service.port }}
      targetPort: {{ .Values.director.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "etherealengine.director.selectorLabels" . | nindent 4 }}
{{- end -}}
