{{- if (.Values.matchfunction).enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etherealengine.matchfunction.fullname" . }}
  namespace: {{ include "etherealengine.matchmaking-namespace" . }}
  labels:
    {{- include "etherealengine.matchfunction.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.matchfunction.replicaCount }}
  selector:
    matchLabels:
      {{- include "etherealengine.matchfunction.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etherealengine.matchfunction.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/matchfunction-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.matchfunction.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "etherealengine.matchfunction.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.matchfunction.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.matchfunction.securityContext | nindent 12 }}
          image: "{{ .Values.matchfunction.image.repository }}:{{ .Values.matchfunction.image.tag }}"
          imagePullPolicy: {{ .Values.matchfunction.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "etherealengine.matchfunction.fullname" . }}
                optional: true
          env:
            - name: KUBERNETES
              value: "true"
            - name: RELEASE_NAME
              value: {{ $releaseName }}
            - name: TAG
              value: {{ .Values.matchfunction.image.tag }}
            - name: MATCHFUNCTION_PORT
              value: {{ quote .Values.matchfunction.service.port }}
            - name: RELEASE_FULLNAME
              value: {{ include "etherealengine.matchfunction.fullname" . }}
            - name: NAMESPACE
              value : {{ include "etherealengine.matchmaking-namespace" . }}
          ports:
            - name: http
              containerPort: {{ .Values.matchfunction.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.matchfunction.resources | nindent 12 }}
      volumes:
      - name: dind-storage
        emptyDir: {}
      {{- with .Values.matchfunction.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.matchfunction.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.matchfunction.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
