{{- if and (.Values.builder).enabled ((.Values.builder).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.builder.serviceAccountName" . }}
  labels:
    {{- include "ir-engine.builder.labels" . | nindent 4 }}
  {{- with .Values.builder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
