{{- if (.Values.bot).enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etherealengine-bot.bot.serviceAccountName" . }}
  labels:
    {{- include "etherealengine-bot.bot.labels" . | nindent 4 }}
    {{- with .Values.bot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
