{{- if (.Values.api).enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etherealengine.api.fullname" . }}
  labels:
    {{- include "etherealengine.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "etherealengine.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "etherealengine.api.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "etherealengine.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "etherealengine.api.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "api"
            - name: KUBERNETES
              value: "true"
            {{ if .Values.sql }}
            - name: MYSQL_USER
              value: {{ .Values.sql.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.sql.database }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.sql.password | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.sql.host | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.sql.port | quote }}
            {{ else if .Values.mariadb }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "etherealengine.mariadb.fullname" . }}
                  {{- end }}
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ .Values.mariadb.externalHost }}
            - name: MYSQL_PORT
              value: {{ .Values.mariadb.externalPort | quote }}
            {{ else }}
            - name: MYSQL_USER
              value: server
            - name: MYSQL_DATABASE
              value: etherealengine
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_HOST
              value: host.minikube.internal
            - name: MYSQL_PORT
              value: 3306
            {{ end }}
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_ADDRESS
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_HOST)"
            - name: REDIS_PORT
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_PORT)"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-redis
                  key: redis-password
            - name: RELEASE_NAME
              value: {{ $releaseName }}
            - name: BUILDER_REPOSITORY
              value: {{ .Values.builder.image.repository }}
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{ if eq .Values.api.extraEnv.STORAGE_PROVIDER "local" }}
          volumeMounts:
            - mountPath: /app/packages/server/upload
              name: file-server
          {{- end }}
      {{ if eq .Values.api.extraEnv.STORAGE_PROVIDER "local" }}
      volumes:
        - name: file-server
        {{ if eq .Values.clusterType "microk8s" }}
          persistentVolumeClaim:
            claimName: file-server-pvc
        {{- end }}
        {{ if eq .Values.clusterType "minikube" }}
          hostPath:
            path: {{ .Values.api.fileServer.hostUploadFolder }}
            type: DirectoryOrCreate
        {{- end }}
      {{- end }}
      initContainers:
        - name: init-redis
          image: busybox:1.28
          command: [ 'sh', '-c', 'until (printf "AUTH $REDIS_PASSWORD\r\nPING\r\n";) | nc $REDIS_ADDRESS $REDIS_PORT ; do echo waiting for redis-master; sleep 2; done' ]
          env:
            - name: REDIS_ADDRESS
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_HOST)"
            - name: REDIS_PORT
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_PORT)"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-redis
                  key: redis-password
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
