{{- if (.Values.api).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "etherealengine.api.fullname" . }}
  labels:
    {{- include "etherealengine.api.labels" . | nindent 4 }}
data:
{{- if .Values.api.extraEnv }}
{{ toYaml .Values.api.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.instanceserver.extraEnv }}
{{ toYaml .Values.instanceserver.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.client.extraEnv }}
{{ toYaml .Values.client.extraEnv | indent 2 }}
{{- end }}
{{- if .Values.api.config }}
  NODE_CONFIG: '{{ mustToJson .Values.api.config }}'
{{- end }}
{{- end -}}
