{{- if (.Values.batchinvalidator).enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name:  {{ template "etherealengine.batchinvalidator.fullname" . }}
spec:
  schedule: "* * * * *"  # Run every minute
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
            - name: batch-invalidator
              image: "{{ .Values.batchinvalidator.image.repository }}:{{ .Values.batchinvalidator.image.tag }}"
              envFrom:
                - configMapRef:
                    name: {{ include "etherealengine.batchinvalidator.fullname" . }}
                    optional: true
              env:
                - name: SERVER_MODE
                  value: "api"
                - name: KUBERNETES
                  value: "true"
                {{ if .Values.sql }}
                - name: MYSQL_USER
                  value: {{ .Values.sql.user }}
                - name: MYSQL_DATABASE
                  value: {{ .Values.sql.database }}
                - name: MYSQL_PASSWORD
                  value: {{ .Values.sql.password | quote }}
                - name: MYSQL_HOST
                  value: {{ .Values.sql.host | quote }}
                - name: MYSQL_PORT
                  value: {{ .Values.sql.port | quote }}
                {{ else }}
                - name: MYSQL_USER
                  value: server
                - name: MYSQL_DATABASE
                  value: etherealengine
                - name: MYSQL_PASSWORD
                  value: password
                - name: MYSQL_HOST
                  value: host.minikube.internal
                - name: MYSQL_PORT
                  value: 3306
                {{ end }}
              command: [
                'npx',
                'cross-env',
                'ts-node',
                '--swc',
                'scripts/run-batch-invalidation.ts'
              ]
          restartPolicy: Never
{{- end }}
