{{- if and (.Values.client).enabled ((.Values.client).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etherealengine.client.serviceAccountName" . }}
  labels:
    {{- include "etherealengine.client.labels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
