{{- if and ((.Values.client).enabled) (((.Values.client).serviceAccount).create) (ne (.Values.client).serveFromApi true) (ne (((.Values.builder.extraEnv).SERVE_CLIENT_FROM_STORAGE_PROVIDER) | default "false") "true") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etherealengine.client.serviceAccountName" . }}
  labels:
    {{- include "etherealengine.client.labels" . | nindent 4 }}
  {{- with .Values.client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
