{{- if and (.Values.instanceserver).enabled ((.Values.instanceserver).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etherealengine.instanceserver.serviceAccountName" . }}
  labels:
    {{- include "etherealengine.instanceserver.labels" . | nindent 4 }}
    {{- with .Values.instanceserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
