{{- if and (.Values.media).enabled ((.Values.media).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etherealengine.media.serviceAccountName" . }}
  labels:
    {{- include "etherealengine.media.labels" . | nindent 4 }}
  {{- with .Values.media.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
