{{- if (.Values.taskserver).enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "etherealengine.taskserver.fullname" . }}
  labels:
    {{- include "etherealengine.taskserver.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "agones.dev"
    resources:
      - fleets
      - fleet
      - fleets.agones.dev
      - gameservers
      - gameserver
      - gameservers.agones.dev
      - gameserversets
    verbs:
      - get
      - list
      - watch
{{- end }}
