{{- if and (.Values.director).enabled ((.Values.director).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.director.serviceAccountName" . }}
  namespace: {{ include "ir-engine.matchmaking-namespace" . }}
  labels:
    {{- include "ir-engine.director.labels" . | nindent 4 }}
  {{- with .Values.director.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
