{{- if and (.Values.matchfunction).enabled ((.Values.matchfunction).serviceAccount).create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ir-engine.matchfunction.serviceAccountName" . }}
  namespace: {{ include "ir-engine.matchmaking-namespace" . }}
  labels:
    {{- include "ir-engine.matchfunction.labels" . | nindent 4 }}
  {{- with .Values.matchfunction.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
