# values for nginx-ingress on EKS using Network Load Balancer

rbac:
  create: true

controller:
  config:
    ssl-redirect: "false"
    server-snippet: |
      listen 8000;
      if ( $server_port = 80 ) {
         return 308 https://$host$request_uri;
      }
  containerPort:
    http: 80
    https: 443
    special: 8000
  service:
    targetPorts:
      http: http
      https: special # SSL termination at the load balancer
    annotations:
      meta.helm.sh/release-name: nginx
      meta.helm.sh/release-namespace: default
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=etherealengine"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ACM Certificate ARN for SSL>"

