apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
type: Opaque
data:
  cluster-secret: {{ .Values.clusterSecret | b64enc }}
  bootstrap-peer-priv-key: {{ .Values.bootstrapPeerPrivateKey | b64enc }}