{{- if and (.Values.client).enabled (ne (((.Values.client).ingress).disabled | default false) true) (ne (((.Values.builder.extraEnv).SERVE_CLIENT_FROM_STORAGE_PROVIDER) | default "false") "true") -}}
{{- $clientFullName := include "ir-engine.client.fullname" . -}}
{{- $apiFullName := include "ir-engine.api.fullname" . -}}
{{- $svcPort := .Values.client.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $clientFullName }}
  labels:
    {{- include "ir-engine.client.labels" . | nindent 4 }}
  {{- with .Values.client.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.client.ingress.tls }}
  tls:
  {{- range .Values.client.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.client.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                {{- if $.Values.client.serveFromApi }}
                name: {{ $apiFullName }}
                {{ else }}
                name: {{ $clientFullName }}
                {{- end }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}

