{{- if (.Values.testbot).enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ir-engine.testbot.fullname" . }}
  labels:
    {{- include "ir-engine.testbot.labels" . | nindent 4 }}
data:
{{- if .Values.testbot.extraEnv }}
{{ toYaml .Values.testbot.extraEnv | indent 2 }}
{{- end }}
{{- end }}
